### PR TITLE
Change modal bottom btns visibility

### LINKED ISSUE #558: 🐞 Different pages and modals renders incorrectly on mobile devices
- Environment: mobile
- Client: android 9.1.0 (chrome), ios 16.3 (safari)

### ✔️ Expected behavior

Should render page with top and bottom browser bars not cropping the page

### ✖️ Actual behavior

It crops the top and the bottom of the page if there is top and bottom bars appeared on mobile. Mostly with forms in modals

### Screenshot / Descriptions

image

image

image

image

### Notes
This bug can be related to `height: 100vh` styles

### PR DESCRIPTION
**Pull request by Chichmarin17**
Closes #558, #559 

### ToDo:
- [x] fix filter modal bottom buttons position
- [x] centered `sign in` button on mobile devices
- [x] test on multiple devices

### CODE REVIEW

File: packages/frontapp/src/app/components/Modal/index.tsx [hunk 1]
```diff
@@ -54,10 +55,14 @@ export const ContentModal = styled.div<IStyleProps>`
   width: 100%;
   margin: auto;
   @media (max-width: ${dimensions.phone_width}) {
-    max-height: 100vh;
+    max-height: 100%;
     padding: ${dimensions.xl} ${dimensions.xs_2};
     border-radius: ${dimensions.base_2} ${dimensions.base_2} 0 0;
     margin: 0;
+    overflow-y: scroll;
```
Comment (IAlexHilimovich) [inline packages/frontapp/src/app/components/Modal/index.tsx:62]: Why scroll and not auto?
Scroll always shows scrollbar, auto - only when needed

Comment (Chichmarin17) [reply packages/frontapp/src/app/components/Modal/index.tsx:62]: Nope, that's not how it works. `Overflow: auto` we can't use here as it set the fixed value to our modal, so it can not be scrolled down if it has too much content within it (only Mozilla provide the scroll when needed), so here I added scrollable modal and hided the scrollbar

**Review by IAlexHilimovich — APPROVED** [review]
