### PR TITLE
Carousel buttons doesnt work

### LINKED ISSUE #606: 🐞 Carousel buttons doesn't work
- Environment:
- Client: desktop, http://localhost:4200/search, http://localhost:4200/item/21

### ✔️ Expected behavior

Carousel on  `Library` and `Item` pages should work

### ✖️ Actual behavior

It doesn't work when clicking on left / right arrows

### Screenshot / Descriptions

image

image

### PR DESCRIPTION
**Pull request by Chichmarin17**
Closes #606 

- ### Reader search page
image

- ### Readed item page
image

- Added story for `Carousel` component
- Small localization fixes
- Refactored `AllBookList` component

### CODE REVIEW

**Comment by IAlexHilimovich** [comment]
Distances between cards are too big on high resolutions. This is how it looks for 4k
image

File: packages/frontapp/src/app/components/CarouselWrapper/index.tsx [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+import { FC, ReactNode } from 'react';
+import { Swiper } from 'swiper/react';
+import ControlPanel from './ControlPanel';
+import SliderButtons from './SliderButtons';
+import { useMediaQuery } from 'react-responsive';
+
+import 'swiper/css';
+
+const DESKTOP_SLIDES_PER_VIEW = 5;
+const LAPTOP_SLIDES_PER_VIEW = 4;
```
Comment (IAlexHilimovich) [inline packages/frontapp/src/app/components/CarouselWrapper/index.tsx:12]: Maybe there is a way to make this number calculated based on known card width, distance between cards and container width?

File: packages/frontapp/src/app/components/CarouselWrapper/index.tsx [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+`;
+
+export interface ICarouselWrapperProps {
+  slidesListLengt?: number;
+  header?: ReactNode;
+  slides?: ReactNode;
+}
+
+const CarouselWrapper: FC<ICarouselWrapperProps> = ({
+  slidesListLengt = 0,
```
Comment (IAlexHilimovich) [inline packages/frontapp/src/app/components/CarouselWrapper/index.tsx:36]: typo in Length

**Review by IAlexHilimovich — CHANGES_REQUESTED** [review]

File: packages/frontapp/src/app/components/CarouselWrapper/index.tsx (hunk 1 above)
Comment (Chichmarin17) [reply packages/frontapp/src/app/components/CarouselWrapper/index.tsx:12]: This is pretty rare condition when the user will check the library with its desktop at all, but no, there are no any other options rather that using swipers `breakpoints`. I could add listener to the window resize, but it is not cost it and could lead later to memory leaks. What can I do here is to add one more breakpoint, but it will make buttons logic too complicated

Comment (Chichmarin17) [reply packages/frontapp/src/app/components/CarouselWrapper/index.tsx:12]: As you can see, there are pretty many other issues with `4k` as we didn't discussed how it will look like on such resolution, many different pages and containers has `100%` width which looks pretty ugly on `4k`

File: packages/frontapp/src/app/components/CarouselWrapper/index.tsx (hunk 2 above)
Comment (Chichmarin17) [reply packages/frontapp/src/app/components/CarouselWrapper/index.tsx]: fixed

File: packages/frontapp/src/app/components/CarouselWrapper/index.tsx (hunk 1 above)
Comment (IAlexHilimovich) [reply packages/frontapp/src/app/components/CarouselWrapper/index.tsx:12]: Full HD is also not looking too great.
Try this
`  const containerRef = useRef<HTMLDivElement>(null);
  const [slidesPerView, setSliderCount] = useState(5);
  const SLIDE_WIDTH = 224;
  const SLIDE_GAP = 32;
  useEffect(() => {
    if (containerRef.current) {
      setSliderCount(Math.ceil((containerRef.current.clientWidth + SLIDE_GAP) / SLIDE_WIDTH));
    }
  }, [containerRef.current]);`
And then
`<CustomSwiper spaceBetween={SLIDE_GAP} slidesPerView={slidesPerView} >`

**Comment by IAlexHilimovich** [comment]
One more thing: slides have different height
image

**Comment by Chichmarin17** [comment]
About slides height, that's how it works now, if you take a look at different pages with cards you'll see that they have different height

File: packages/frontapp/src/app/components/CarouselWrapper/index.tsx (hunk 1 above)
Comment (IAlexHilimovich) [reply packages/frontapp/src/app/components/CarouselWrapper/index.tsx:12]: Forgot one thing - need to wrap in div:
```
<div ref={containerRef}>
<CustomSwiper spaceBetween={SLIDE_GAP} slidesPerView={slidesPerView} >
</div>
```

**Comment by IAlexHilimovich** [comment]
> About slides height, that's how it works now, if you take a look at different pages with cards you'll see that they have different height

I think they should be the same height inside same slider

**Comment by Chichmarin17** [comment]
I mean we also have books that have no statuses at all (locally). Lets move `card` height to a separate ticket as it isn't fully related to this task

**Comment by Chichmarin17** [comment]
`full hd`
image
`4k` (area)
image

Also, I make control buttons render only if they are needed (slides > slidesPerView). Thanks for the idea with refs

File: packages/frontapp/src/app/components/CarouselWrapper/index.tsx (hunk 1 above)
Comment (Chichmarin17) [reply packages/frontapp/src/app/components/CarouselWrapper/index.tsx]: I've already got it) Thanks

File: packages/frontapp/src/app/components/CarouselWrapper/index.tsx [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+  }, [containerRef.current]);
+
+  const shouldShowControls = slidesPerView >= slidesListLength;
+
+  return (
+    <SwiperWrapper ref={containerRef}>
+      <CustomSwiper slidesPerView={slidesPerView} spaceBetween={SLIDE_GAP}>
+        <ControlPanel
+          title={header}
+          controlButtons={shouldShowControls ?? <SliderButtons />}
```
Comment (IAlexHilimovich) [inline packages/frontapp/src/app/components/CarouselWrapper/index.tsx:59]: Buttons are not displayed if shouldShowControls = true
Should be `&&` instead of `??`
Also when they are displayed - they don't work

Comment (Chichmarin17) [reply packages/frontapp/src/app/components/CarouselWrapper/index.tsx]: fixed

**Review by IAlexHilimovich — APPROVED** [review]
